### ISSUE TITLE
emby无法现在女优照片，运行添加头像程序出错

### ISSUE THREAD

**Issue by pkr5277** [javsdt/javsdt#92]
![photo_2020-06-22_09-22-50](https://user-images.githubusercontent.com/38154917/85240330-68712500-b46a-11ea-9a23-8df21023ff63.jpg)
![photo_2020-06-22_09-22-55](https://user-images.githubusercontent.com/38154917/85240335-6ad37f00-b46a-11ea-9424-3023f457f789.jpg)
运行程序报错，emby里的api id填写正确

**Comment by SeanChengN** [comment]
配置文件也截个图，api那里

**Comment by pkr5277** [comment]
![image](https://user-images.githubusercontent.com/38154917/85351583-bd7a6d00-b536-11ea-8265-7b9b0933076d.png)

**Comment by SeanChengN** [comment]
填e5*****d7这段

**Comment by pkr5277** [comment]
大老牛逼，问题解决
